#
#Wed Mar 04 05:35:53 UTC 2026
acceptInsecureCerts=false
browserName=chrome
goog\:chromeOptions={args\=[remote-allow-origins\=*, --headless\=chrome, --headless,--no-sandbox,--disable-dev-shm-usage,--disable-gpu,--remote-debugging-port\=9222, --headless], extensions\=[]}
